apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: test
deploy:
  helm:
    releases:
      - name: test-v2
        chartPath: ./charts/test
        valuesFiles:
          - ./charts/test/values.yaml
          - ./charts/test/secrets.values.yaml
        createNamespace: true
        namespace: test-v2
        useHelmSecrets: true
